-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "passwordChangedAt" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "whatsappApiKey" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "telegramChatId" TEXT;
